### PR TITLE
Fix: use json payloads

### LINKED ISSUE #33: rust-sdk doesn't support json publish / subscribe
Use case:
During libp2p interop testing, we have a test instance, written in go, that publishes a JSON payload.
It's causing a panic in the rust instances.

Example stack trace:

```
Jul 21 15:35:51.224502  INFO    2.5231s    MESSAGE << go-v0.20[000] (a78c77) >> my listen addrs: [/ip4/16.3.0.3/tcp/37119]
Jul 21 15:35:51.260018  INFO    2.5588s      ERROR << rust-v0.47.0[000] (a36242) >> thread 'tokio-runtime-worker' panicked at 'JSON Deserialization: Error("invalid type: map, expected a string", line: 1, column: 0)', /usr/local/cargo/git/checkouts/sdk-rust-13727f1421bc2391/d6af289/src/responses.rs:63:54
Jul 21 15:35:51.260053  INFO    2.5588s      ERROR << rust-v0.47.0[000] (a36242) >> stack backtrace:
Jul 21 15:35:51.269283  INFO    2.5680s      ERROR << rust-v0.47.0[000] (a36242) >>    0: rust_begin_unwind
Jul 21 15:35:51.269325  INFO    2.5681s      ERROR << rust-v0.47.0[000] (a36242) >>              at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
Jul 21 15:35:51.269353  INFO    2.5681s      ERROR << rust-v0.47.0[000] (a36242) >>    1: core::panicking::panic_fmt
Jul 21 15:35:51.269393  INFO    2.5682s      ERROR << rust-v0.47.0[000] (a36242) >>              at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
Jul 21 15:35:51.269425  INFO    2.5682s      ERROR << rust-v0.47.0[000] (a36242) >>    2: core::result::unwrap_failed
Jul 21 15:35:51.269444  INFO    2.5682s      ERROR << rust-v0.47.0[000] (a36242) >>              at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1785:5
Jul 21 15:35:51.269461  INFO    2.5682s      ERROR << rust-v0.47.0[000] (a36242) >>    3: <testground::responses::Response as core::convert::From<testground::responses::RawResponse>>::from
Jul 21 15:35:51.269484  INFO    2.5683s      ERROR << rust-v0.47.0[000] (a36242) >>    4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jul 21 15:35:51.269502  INFO    2.5683s      ERROR << rust-v0.47.0[000] (a36242) >>    5: tokio::runtime::task::harness::poll_future
Jul 21 15:35:51.269526  INFO    2.5683s      ERROR << rust-v0.47.0[000] (a36242) >>    6: tokio::runtime::task::harness::Harness<T,S>::poll
Jul 21 15:35:51.269544  INFO    2.5683s      ERROR << rust-v0.47.0[000] (a36242) >>    7: std::thread::local::LocalKey<T>::with
Jul 21 15:35:51.269562  INFO    2.5683s      ERROR << rust-v0.47.0[000] (a36242) >>    8: tokio::runtime::thread_pool::worker::Context::run_task
Jul 21 15:35:51.269578  INFO    2.5683s      ERROR << rust-v0.47.0[000] (a36242) >>    9: tokio::runtime::thread_pool::worker::Context::run
Jul 21 15:35:51.269595  INFO    2.5684s      ERROR << rust-v0.47.0[000] (a36242) >>   10: tokio::macros::scoped_tls::ScopedKey<T>::set
Jul 21 15:35:51.269625  INFO    2.5684s      ERROR << rust-v0.47.0[000] (a36242) >>   11: tokio::runtime::thread_pool::worker::run
Jul 21 15:35:51.269693  INFO    2.5684s      ERROR << rust-v0.47.0[000] (a36242) >>   12: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
Jul 21 15:35:51.269721  INFO    2.5685s      ERROR << rust-v0.47.0[000] (a36242) >>   13: tokio::runtime::task::harness::Harness<T,S>::poll
Jul 21 15:35:51.269742  INFO    2.5685s      ERROR << rust-v0.47.0[000] (a36242) >>   14: tokio::runtime::blocking::pool::Inner::run
Jul 21 15:35:51.269762  INFO    2.5685s      ERROR << rust-v0.47.0[000] (a36242) >> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

My understanding is that this code expects a string:
https://github.com/testground/sdk-rust/blob/d6af289b7ce0d58185b4918f424c7f2aacdd4200/src/responses.rs#L61-L64

But receive a JSON payload like 
```{"Addrs":["/ip4/16.3.0.3/tcp/45369"],"ID":"QmbSLMEMackm7vHiUGMB2EFAPbzeJNpeB9yTpzYKoojDWc"}```

We want to use something like `Subscribe(serde_json::Value)` instead of `Subscribe(msg)` in the Reponse type.

### PR DESCRIPTION
**Pull request by laurentsenta**
Fixes #33,

- [x] Uses a json payload for publish / subscribes,
- [x] introduce `publish-subscribe` example, which demonstrate leader / follower pattern with JSON payloads.

### CODE REVIEW

**Comment by laurentsenta** [comment]
(Sorry for the noise, please ignore for now, I'll make sure the interop test are passing before review)

**Comment by mxinden** [comment]
@laurentsenta thanks for working on this. Let me know in case you need any help.

**Comment by mxinden** [comment]
Thinking about this some more and running the failing tests myself, I think instead of serializing and deserializing a JSON structure in sdk-rust, we should leave it up to the user of sdk-rust what to send, and instead do the serialization and deserialization in the concrete test plans.

The benefit is, that a user can publish any format and is not bound to JSON.

@laurentsenta what do you think?

File: src/responses.rs [hunk 1]
```diff
@@ -58,11 +76,7 @@ impl From<RawResponse> for Response {
                 let error = serde_json::from_str(&error).expect("JSON Deserialization");
                 ResponseType::Error(error)
             }
-            (None, Some(msg), None, None) => {
-                //Hack to remove extra escape characters
-                let msg = serde_json::from_str(&msg).expect("JSON Deserialization");
-                ResponseType::Subscribe(msg)
```
Comment (mxinden) [inline src/responses.rs:64]: With the suggestion above, we would only do the following patch here:

``` diff
-               //Hack to remove extra escape characters
-               let msg = serde_json::from_str(&msg).expect("JSON Deserialization");
                ResponseType::Subscribe(msg)
```

**Comment by mxinden** [comment]
@SionoiS you probably have an opinion here?

**Comment by SionoiS** [comment]
The problem was that serde can't deal with nested json strings AFAIK.

Either we don't deserialize OR we write something custom.

Writing something could allow to remove the ugly RawResponse -> Response conversion.
https://github.com/testground/sdk-rust/blob/d6af289b7ce0d58185b4918f424c7f2aacdd4200/src/responses.rs#L44

@laurentsenta is going in the right direction I think. Using serde_json::Value allow users to use their own types.

File: src/responses.rs (hunk 1 above)
Comment (laurentsenta) [reply src/responses.rs:64]: > Thinking about this some more and running the failing tests myself, I think instead of serializing and deserializing a JSON structure in sdk-rust, we should leave it up to the user of sdk-rust what to send, and instead do the serialization and deserialization in the concrete test plans.
> 
> The benefit is, that a user can publish any format and is not bound to JSON.

Could you share the benefits you see?
My thinking might be "tainted" by the go-sdk but I think defaulting to JSON is a good thing:

* Test implementers don't have to think about serialization schemes,
* SDKs can automate encoding/decoding (the go SDK uses reflection to convert JSON payloads from/to Go structures),
* It's hard to create a JSON payload that cannot be used from another language
  * I'm seeing this now with the libp2p/ping go test, they publish a JSON we can use in Rust without much effort. If they had come up with their scheme, best case scenario we would use JSON, worst case we now have to support protocol buffer or a custom encoding.

For what it's worth, it looks like there is a type issue in the API that makes it confusing, but we don't have to leak this on the user side:
https://github.com/testground/sync-service/blob/d3e9e3e56403ed994f350942813d3d8aa746debc/types.go#L21
https://github.com/testground/sync-service/blob/d3e9e3e56403ed994f350942813d3d8aa746debc/types.go#L69
(string response)

**Comment by mxinden** [comment]
Thanks @laurentsenta and @SionoiS for the quick responses.

:+1: for proceeding in the direction this pull request is heading.

File: examples/example.rs [hunk 2]
```diff
@@ -11,7 +23,51 @@ async fn main() -> Result<(), Box<dyn std::error::Error>> {
...
     ));
 
+    let json = serde_json::json!({"foo": "bar"});
+    client.publish("demonstration", Cow::Owned(json)).await?;
     client.record_success().await?;
 
     Ok(())
 }
+
+async fn publish_subscribe(
```
Comment (mxinden) [inline examples/example.rs:33]: Thank you for providing an example along with your patch. This is great engineering.

Given that the old `fn example` is quite simple, I would be fine for `fn publish_subscribe` to replace it. Just an idea to reduce complexity. Not a strong opinion.

File: src/responses.rs [hunk 3]
```diff
@@ -54,14 +54,14 @@ impl From<RawResponse> for Response {
...
-                //Hack to remove extra escape characters
+                // Hack to remove extra escape characters
                 let error = serde_json::from_str(&error).expect("JSON Deserialization");
                 ResponseType::Error(error)
             }
             (None, Some(msg), None, None) => {
-                //Hack to remove extra escape characters
-                let msg = serde_json::from_str(&msg).expect("JSON Deserialization");
-                ResponseType::Subscribe(msg)
+                // the Subscribe payload is a json encoded string, so we need to deserialize it
```
Comment (mxinden) [inline src/responses.rs:62]:
```suggestion
                // The Subscribe payload is a json encoded string, so we need to deserialize it.
```

**Review by mxinden — APPROVED** [review]
Thank you @laurentsenta for the fix.

This looks good to me overall.

I am not sure why CI is failing, since the container reports a success.

File: examples/example.rs (hunk 2 above)
Comment (laurentsenta) [reply examples/example.rs:31]: Thanks for the feedback @mxinden!
If you don't mind I would keep it, not as test cases, I agree it's not really useful, but as an example for future users. I like the idea of having a really bare minimum "here is how you write a test that passes in testground", before moving into more complex synchronization patterns.

**Comment by laurentsenta** [comment]
@mxinden that's exciting, we might have a minimal example of testground going unstable. Investigating

**Comment by laurentsenta** [comment]
@mxinden I might have a patch, but it'll take some time to finalize (https://github.com/testground/testground/pull/1406) do you think we could merge on a green pass (since it's testground related)?

**Comment by mxinden** [comment]
:pray: Thanks @laurentsenta for tackling this. Moving forward sounds good to me.
